version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5430:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker

volumes:
  pgdata: